config/routes.rb
Rails.application.routes.draw do

  resources :events
  
  resources :people
    get "/welcome/say_hello" => "welcome#say"

    get "welcome" => "welcome#index"

  root 'welcome#index'

  match ':controller(/:action(/:id(.:format)))', :via => :all
end

app/models/event.rb
class Event < ActiveRecord::Base
    
    validates_presence_of :name
    #資料驗證  名子欄位必填
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :set_event, :only => [:show, :edit , :update, :destroy]
    #程式執行action之前會先呼叫set_event方法,並指定
    def index
        #@events = Event.all  (修改前)
        @events = Event.page(params[:page]).per(10)
        #安裝完kaminari分頁外掛,用分頁方式
        #撈出所有資料以每頁10筆
    end

    def show
        @page_title = @event. name
        #撈到文章的name 給一個變數
    end

    def new
        @event = Event.new
        #初始化一個資料庫還沒儲存
    end

    def create
        @event = Event.new(event_params)

        if @event.save #save 有回傳值true和false
        #成功存起來

           flash[:notice] = "新增成功"
            #成功可以顯示訊息,需要先在layouts設定
            redirect_to events_path
        #轉到 index 頁面
        else
            render :action => :new 
            #失敗的話這裡是顯示new.html.erb,所以不是真的執行action
           # 可以省略:action
        end
    end

    def edit

    end

    def update
        if @event.update(event_params)

            flash[:notice] = "編輯成功"

            redirect_to event_path(@event)
        #轉向頁面到show action ,單數所以要加參數
        else
            render :action => :edit
        end
    end

    def destroy
        @event.destroy
        #刪除
        flash[:alert] = "刪除成功"
        
        redirect_to events_path
    end


    private

    def set_event
        @event = Event.find(params[:id])
        #根據每篇文章ID從event資料庫找出資料來
    end

    def event_params
        params.require(:event).permit(:name, :description)
         #針對event 只允許存取 name 和description
    end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :bio, :birthday)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
    def index

    end
    

    def say

    end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
<!-- 假如 @event 有任何錯誤 -->
    <ul>
        <% @event.errors.full_messages.each do |msg| %>
        <!-- 把全部的錯誤一個一個印出來-->
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<p>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
</p>

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event), :method => :patch do |f| %>
<!-- 當表單送出會送到update action , edit 是單數根據文章的ID 所以要加上參數＠event ,有待驗證 -->

    <%= render :partial => "form", :locals => { :f => f } %>
    <!-- paritial 局部樣板 渲染_form 這個檔案,傳遞區域變數過來這裡(有待驗證)-->



    <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<h1>Events list</h1>

<ul>
<% @events.each do |e| %>
<li>
    <%= e.name %>

    <%= link_to "show", event_path(e) %>
     <!--  show 是單數-->
    <%= link_to "edit", edit_event_path(e) %>
    
    <%= link_to "Delete", event_path(e), :method => :delete %>
    <!--  超連結http預設是 get ,這裡指定delete   
       也可以寫成這樣   method: "delete" -->

</li>

<% end %>
</ul>

<%= link_to 'New Event', new_event_path %>


<%= paginate @events %>
<!-- kaminari 外掛提供view helper 產生分頁功能-->

app/views/events/new.html.erb
<%= form_for @event, :url => events_path do |f| %>

<!-- 當你按下按鈕 會送到 events controller 的create action -->

    <%= render :partial => "form", :locals => { :f => f } %>
 <!-- paritial 局部樣板 渲染_form 這個檔案,傳遞區域變數過來這裡(有待驗證)-->

    <%= f.submit "Create" %>

<% end %>

app/views/events/show.html.erb
<h2><%= @event.name %></h2>

<%= simple_format@event.description %>
<!--simple_format 是rails helper 換行時自動加上html  <br> 換行標籤
-->

<p><%= link_to "Back to index", events_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Demo" %></title>
  <!-- 從events controller 的 show action  傳來 ,顯示文章標題,沒標題顯示Demo  -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <p style="color: green"><%= flash[:notice] %></p>
    <p style="color: red"><%= flash[:alert] %></p>
    <!--有設定的話可以顯示錯誤訊息 -->

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.bio %></td>
        <td><%= person.birthday %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @person.birthday %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/welcome/index.html.erb
<p>Hola! It's<%= Time.now %></p>
<p><%= link_to 'hello!', welcome_say_hello_path %></p>

app/views/welcome/say.html.erb
<h2>Hello world</h2>